### ISSUE TITLE
Getting a scheme not valid error

### ISSUE THREAD

**Issue by luis-cortina** [IdentityModel/IdentityModel.OidcClient.Samples#103]
@GioviQ including you here according to the ReadMe on the Xamarin Forms example.
Your example was working ok until installing iOS 14.5, is throwing the following error:
![image](https://user-images.githubusercontent.com/25346332/116309594-2d184480-a766-11eb-8247-7b53f88262bb.png)

If I run your example it works fine, any idea where to look here?

Luis

**Comment by GioviQ** [comment]
I am not working on this repository. Sorry.

**Comment by leastprivilege** [comment]
![image](https://user-images.githubusercontent.com/1454075/116368186-5ee1e780-a808-11eb-95d0-1e1eeba67b32.png)

OK - then there was a misunderstanding. I will delete the sample.

**Comment by MarkusHorstmann** [comment]
It appears that the fix (or at least a workaround) is https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/main/XamarinForms/XamarinFormsClient/XamarinFormsClient.iOS/ASWebAuthenticationSessionBrowser.cs, line 29:
-                       options.EndUrl,
+                      new NSUrl(options.EndUrl).Scheme,
