### ISSUE TITLE
Replacement for AuthorizeResponseMode.Redirect in version 4.0.0.0

### ISSUE THREAD

**Issue by Spike433** [IdentityModel/IdentityModel.OidcClient.Samples#114]
ResponseMode = OidcClientOptions.**AuthorizeResponseMode.Redirect** is used in version 3.0.0.0 but missing in 4.0.0.0, what is replacement?

**Comment by brockallen** [comment]
That's the highlander setting. 

![image](https://user-images.githubusercontent.com/649492/131381919-1134d421-30da-4dc6-9c6b-de4ca8cf825b.png)

**Comment by Spike433** [comment]
I will use 3.1.2 then, thanks anyway.

**Comment by brockallen** [comment]
Heh, sorry -- perhaps you misunderstood the joke. Given that code flow is the only real flow these days, the response mode only ever needs to be redirect (more specifically query), and thus I'm guessing that's why it was removed. HTH :)

**Comment by Spike433** [comment]
Either way joke was funny, yeah, you are right, it works perfectly without it. 
Still I will go with 3.1.2. 
Thanks 💯
