### ISSUE TITLE
ConsoleSystemBrowser fails when using Steam openid URL.

### ISSUE THREAD

**Issue by MyOwnClone** [IdentityModel/IdentityModel.OidcClient.Samples#12]
Hi,
I am trying to edit your ConsoleSystemBrowser to use it for OpenID sign in to Steam. I have changed Program.cs options initialization this way:

```
var options = new OidcClientOptions
 {
     Authority = "https://steamcommunity.com/openid",
     ClientId = "native.hybrid",
     Scope = "openid profile api",
     RedirectUri = redirectUri
};
```

but I get following error on the call:
`var state = await client.PrepareLoginAsync();`

error is as follows:

`Error loading discovery document: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.`

When I look at given URL (https://steamcommunity.com/openid), I got following XML:

```
<?xml version="1.0" encoding="UTF-8"?>
<xrds:XRDS xmlns:xrds="xri://$xrds" xmlns="xri://$xrd*($v*2.0)">
	<XRD>
		<Service priority="0">
			<Type>http://specs.openid.net/auth/2.0/server</Type>		
			<URI>https://steamcommunity.com/openid/login</URI>
		</Service>
	</XRD>
</xrds:XRDS>
```

Seems like library parser crashes on the first character, the '<', so it looks like it is not expecting XML at all as a discovery document...

**Comment by leastprivilege** [comment]
OpenID is not OpenID Connect

https://openid.net/specs/openid-connect-migration-1_0.html

..and thus not supported by this library.
