### ISSUE TITLE
WPF:  Google Auth  - This browser or app may not be secure

### ISSUE THREAD

**Issue by romantitov** [IdentityModel/IdentityModel.OidcClient.Samples#121]
I use Identity Server with Google authentication from this example [3_AspNetCoreAndApis](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v5/Quickstarts/3_AspNetCoreAndApis) (the same issue I see with [IdentityServer4.Demo](https://github.com/IdentityServer/IdentityServer4.Demo))
Wen I open google authentication page and enter my email I see the following page:
![image](https://user-images.githubusercontent.com/11888679/161094444-30e6f205-7047-46d5-b69e-052ad71ec218.png)

Is there any way to make the browser more secure?

**Comment by leastprivilege** [comment]
Google blocks WebViews - you must use the system browser.
