### ISSUE TITLE
How to handle 2FA enabled situation?

### ISSUE THREAD

**Issue by surensaluka** [IdentityModel/IdentityModel.OidcClient.Samples#123]
Hi,
I want to implement 2FA (Send code by email) with the OidcClient library on a **UWP** app. So from the backend web (Which uses Microsft identity and Identity Server), 2FA is on, and when I call the token endpoint I need to identify that 2FA is on. Is this library can handle such a situation?

This is regarding password flow.
My apologies if this is not relevant.

**Comment by leastprivilege** [comment]
This library does not support password flow. It's an anti-pattern. Do your 2FA in the browser instead.
