### ISSUE TITLE
There are no remote procedure calls active on this thread - MAUI

### ISSUE THREAD

**Issue by Rufistofeles** [IdentityModel/IdentityModel.OidcClient.Samples#124]
Hi there, 
I was testing the MAUI example on windows machine but when I clicked on the "Login" button it returns this exception: 
![image](https://user-images.githubusercontent.com/5821026/173170068-1d9c61b3-004f-41f1-881c-229192a7550b.png)

Somebody knows why?

**Comment by leastprivilege** [comment]
<img width="732" alt="image" src="https://user-images.githubusercontent.com/1454075/173174668-c06e074f-fd28-4970-8bdf-02646bf7fc8b.png">

Windows is an inferior OS with no built-in authentication browser.

**Comment by oliverw** [comment]
> <img alt="image" width="732" src="https://user-images.githubusercontent.com/1454075/173174668-c06e074f-fd28-4970-8bdf-02646bf7fc8b.png">
> 
> Windows is an inferior OS with no built-in authentication browser.

Total bummer that more than half a year later, this is still the case.
