### ISSUE TITLE
IdentityModel.OidcClient: how validating generated access token whit curl (%oidcServer%/token/introspect)

### ISSUE THREAD

**Issue by gguaita** [IdentityModel/IdentityModel.OidcClient.Samples#157]
I'm using sample WindowsConsoleSystemBrowser and get the access token generated from keycloak. 
Subsequently, I try to validate the token with curl at address <oidcServer>/token/introspect but the token is not valid.
How generate or validate this access code correctly?

**Comment by josephdecock** [comment]
This sounds like an issue that would best be addressed by the keycloak folks who will be able to better help you configure your token server and understand any errors its giving you.

**Comment by gguaita** [comment]
Maybe I forgot a detail. If I get a token with curl, I can also validate it with curl. if I get a token with IdentityModel I can't validate it with curl.

**Comment by gguaita** [comment]
I figured out where the problem lay with Keycloack's technicians.
https://stackoverflow.com/questions/53721588
*You need to make sure that you introspect the token using the same DNS hostname/port as the request. Unfortunately that's a not widely documented "feature" of Keycloak...*

Thank you for your attention
