### ISSUE TITLE
Is it possible to use IdentityModel.OidcClient for a non-PKCE flow?

### ISSUE THREAD

**Issue by gregmercer** [IdentityModel/IdentityModel.OidcClient.Samples#16]
I'm trying to see if it is possible to use IdentityModel.OidcClient for a flow that (I believe) does not support PKCE.

Specifically, I'm trying to go to:
 Authority = "https://accounts.google.com"
using: 
 Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode

But when I do I get back the message:
  'Error redeeming code: A task was cancelled.'

I'm guessing this might mean that the Google OAuth may not support PKCE (but not sure how to know).

Here is the specific code I've changed in the IOSClient sample.
```
var options = new OidcClientOptions
{
    Authority = "https://accounts.google.com",
    ClientId = "########.apps.googleusercontent.com",
    Scope = "profile",
    RedirectUri = "edu.stanford.gsb.gsbgo:/oauth2redirect",
    Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode,
    
    TokenClientAuthenticationStyle = IdentityModel.Client.AuthenticationStyle.BasicAuthentication,

    ProviderInformation = new ProviderInformation
    {
        IssuerName = "accounts.google.com",
        AuthorizeEndpoint = "https://accounts.google.com/o/oauth2/v2/auth",
        TokenEndpoint = "https://www.googleapis.com/oauth2/v4/token",
        KeySet = new JsonWebKeySet()
    },

    ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect
};
```

**Comment by leastprivilege** [comment]
Since this is a spec compliant client we required PKCE.

But I am sure Google supports it as well. In fact the author of the napps spec is a Google employee - see his reference implementation here:

https://github.com/openid/AppAuth-iOS
