### ISSUE TITLE
Error using IdentityServer3

### ISSUE THREAD

**Issue by Rajivhost** [IdentityModel/IdentityModel.OidcClient.Samples#17]
Hi,
I try to use IdentityModel.OidcClient with my IdentityServer3, but when I call LoginAsync() method I got the error below:

**Error loading discovery document: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.**

**Comment by leastprivilege** [comment]
Try to browser to the disco doc and see what you get. Or use fiddler to see what happens on the wire.

**Comment by Rajivhost** [comment]
I get this:

![image](https://cloud.githubusercontent.com/assets/3539984/24947763/ebc3a994-1f5f-11e7-87da-c1097e4e0427.png)

**Comment by leastprivilege** [comment]
Which looks good to me. How do your OidcClientOptions look like. Also trace the network traffic with Fiddler to see whats going on,

**Comment by Rajivhost** [comment]
This is my OidcClientOptions:

![image](https://cloud.githubusercontent.com/assets/3539984/24949334/233ad1ae-1f65-11e7-8be3-4b15ec5a9141.png)

I can see the requests arrives on my server
![image](https://cloud.githubusercontent.com/assets/3539984/24951025/e59103d6-1f6a-11e7-9b8d-2307802fbadd.png)

and this is what I got on Fiddler:
![image](https://cloud.githubusercontent.com/assets/3539984/24951082/1bdd5a0c-1f6b-11e7-9dcd-061e6907c7ca.png)

**Comment by Rajivhost** [comment]
I think The localhost:49157 is my SignalR communication.

**Comment by Rajivhost** [comment]
When I try it over https, I got this error:

**Error loading discovery document: Error connecting to https://localhost:2803/.well-known/openid-configuration: An error occurred while sending the request.**

**Comment by Rajivhost** [comment]
I think I figure out what wrong, was my mistake. I forget that I pipe my hosted IdentityServer3 on /identity on my server.

**Comment by leastprivilege** [comment]
That Fiddler trace is useless. Sorry you need to fix that somehow yourself. Seems to be a network config issue.
