### ISSUE TITLE
Is it possible to set it so it doesn't require ssl(https)

### ISSUE THREAD

**Issue by nertilpoci** [IdentityModel/IdentityModel.OidcClient.Samples#18]
I have setup an identity server to a host that doesn't have ssl certificate hence i don't have https.
But i get the error that Https Required
```C#

var options = new OidcClientOptions
            {
                Authority = _authority,
                
                ClientId = "native.hybrid",
                RedirectUri = redirectUri,
                Scope = "openid profile api1 email",
                FilterClaims = false,
                Browser = _browser,
                
                  
                

            };
```

I can access the .wellknown from the browser also can access using the discovery client which has a property for RequireSsl
```C#
var client = new DiscoveryClient("http://mywebsite.net"); 

           client.Policy.RequireHttps = false;
            var disco = await client.GetAsync();
```

Thanks Nertil

**Comment by ByteNuts** [comment]
Hi,

Just set the policy on the OidcClientOptions.


`                Policy = new Policy
                {
                    Discovery = new DiscoveryPolicy
                    {
                        RequireHttps = false
                    }
                },
`

Cheers,
João

**Comment by nertilpoci** [comment]
Thanks man, saved me a lot of time
