### ISSUE TITLE
Will there be a WPF Sample?

### ISSUE THREAD

**Issue by bzuillsmith** [IdentityModel/IdentityModel.OidcClient.Samples#21]
Are there plans to add a WPF sample? I see UWP has a Web Authentication Broker but I don't believe WPF has anything quite like that. My guess is I'll have to do something similar to WinForms example but it'll take some study because I know very little about the WebBrowser for WPF.

**Comment by leastprivilege** [comment]
> but it'll take some study

Same for me. If you are have it figured out, feel free to contribute to the samples repo.

**Comment by nertilpoci** [comment]
@bzuillsmith  i have implemented this using the .netcoreconsole sample implementation and using a wpf browser so it doesn't open the default browser. [](https://github.com/nertilpoci/TriggerME/tree/master/TriggerMeClient.Wpf) maybe this can help you

**Comment by bzuillsmith** [comment]
@nertilpoci ah! I hadn't thought of that. I will give it a try.

I spent some time attempting it with the WPF ```WebBrowser``` class but the navigating events do not give you access to the request and response data. The ```WebRequest``` property is defined on the ```NavigatingCancelEventArgs``` class, but I read in some documentation that it is always ```null``` for several controls including the ```WebBrowser``` making the events pretty much useless.

That leaves me to with @nertilpoci's idea or wrapping the WinForms extended web browser in some kind of host control for use in WPF.

**Comment by nertilpoci** [comment]
@bzuillsmith  i ended up modifying the [SystemBrowser.cs ](https://github.com/nertilpoci/TriggerME/blob/master/TriggerMeClient.Wpf/SystemBrowser.cs) to use [awesomium browser for wpf](http://wiki.awesomium.com/) because the built in webcontrol wasn't showing the css of my login page correctly but it should work with any browser as long as you implement `IdentityModel.OidcClient.Browser.IBrowser`

**Comment by leastprivilege** [comment]
Last time I tried the WPF browser control was good enough - 

use this starting point
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/WpfOidcClient/LoginWebView.xaml.cs

**Comment by bzuillsmith** [comment]
@leastprivilege I actually took the sample from your [blog post on using HttpListener](https://leastprivilege.com/2016/07/08/update-for-authentication-api-access-for-native-applications-and-identitymodel-oidcclient/) to listen for the redirect. That combined with using the ```WebBrowser``` to show the login form seems to have worked for me in a basic sample. I haven't tested it a ton and thought through much of the edge cases and error handling yet. The ```HttpListener``` seems like a light-weight version of what the  NetCoreConsole sample is doing because that sample starts a temporary Kestrel server to handle the redirected data.

I don't totally follow what is happening in that WpfOidcClient  (v3) sample that is reading all the input fields into a uri so it is hard for me to tell what is better. Is reading data from the form itself still a viable approach in oidcclient4? I'm still familiarizing myself with the oidc flow and where all the data is coming from in this case.

**Comment by leastprivilege** [comment]
Well - first of all you need to make up your mind if you want to use a browser control or the system browser.

**Comment by bzuillsmith** [comment]
I am definitely using the WPF WebBrowser control... Trying to keep the process in the app

**Comment by leastprivilege** [comment]
then just handle the navigation event.

**Comment by bzuillsmith** [comment]
As I mentioned before, the navigation event doesn't provide anything but the URI (the properties like ```WebRequest``` are always null for the ```WebBrowser``` class). Therefore, I can't pull the request data out of it when it redirects to the endUrl. But maybe I'm not understanding something about how to grab the data from the WebBrowser?

**Comment by leastprivilege** [comment]
I already pointed you to the sample - here it is again:

https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/WpfClient/LoginWebView.xaml.cs#L38

Once you have the IBrowser implementation for WPF done - it would be cool if you contribute that.

**Comment by bzuillsmith** [comment]
Yeah, sorry. I saw the sample. I didn't understand how the sample you gave worked until now. I went and read more of the OpenID spec, particularly for form_post response mode and I get it now. Looks like I was making it more complicated and reinventing the wheel. Should be very similar to your v3 sample.

I hope to submit a PR at the end of this week. Thanks!

**Comment by COBRASoft5** [comment]
Any news on the WPF sample? Thx!

**Comment by leastprivilege** [comment]
The WPF sample has been added.
