### ISSUE TITLE
Where store/manage the client secret in mobile app

### ISSUE THREAD

**Issue by Jenan** [IdentityModel/IdentityModel.OidcClient.Samples#23]
Hello,

I want to create the mobile app (using Xamarin) and I am wondering about using the hybrid flow with client secret but I don't know where store the client secret and how manage this client secret if it is necesarry the client secret change then is it required release new version of my app? Or is it recommended use the client secret for mobile?

Thank you.

**Comment by leastprivilege** [comment]
Unless you are doing dynamic client registration - client secrets are not recommended for mobile (aka public) clients

**Comment by Jenan** [comment]
Is it possible doing - dynamic client registration in the identityserver4?

**Comment by leastprivilege** [comment]
no. don't bother with a secret. It doesn't give you more security.

**Comment by Jenan** [comment]
OK - in Xamarin app - is there some recommended place for storing tokens? Thx.

**Comment by leastprivilege** [comment]
Depends on OS — e.g. keychain on iOS.
