### ISSUE TITLE
ChromeCustomTab Callback missing startActivity

### ISSUE THREAD

**Issue by SDV-MINI-DEV-2** [IdentityModel/IdentityModel.OidcClient.Samples#24]
Hi,
look at callback:
`https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/AndroidClientVS2017/AndroidClient/OidcCallbackActivity.cs`

doesn't it miss this
`StartActivity(typeof(MainActivity));`

after
`Callbacks?.Invoke(Intent.DataString);`

In past examples it was like that.

`https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/AndroidClientChromeCustomTabs/AndroidClientChromeCustomTabs/CallbackInterceptorActivity.cs`

**Comment by brockallen** [comment]
Yea, that's something I've been struggling with how to port over. When the browser does not have SSO, then that line is needed. If you already have SSO in the browser then that line is not right.

**Comment by leastprivilege** [comment]
@brockallen could you please remove all Android samples and just leave "the one" working in there?

**Comment by brockallen** [comment]
I left the vs2015 one for those who were still on the prior version.

**Comment by leastprivilege** [comment]
There's a newer Xamarin Forms sample that includes Android.
