### ISSUE TITLE
Sample broken with latest OidClient 2.3.0

### ISSUE THREAD

**Issue by zyofeng** [IdentityModel/IdentityModel.OidcClient.Samples#25]
Hi, if I update the library to 2.3.0 the application exits itself (AndroidClientVS2017\AndroidClient)

Version of Support.CustomTabs is still on 25.4.0.2

I have tried LoginAsync with LoginRequest as well and the application never reached that line.

**Comment by leastprivilege** [comment]
Maybe try the new Xamarin Forms sample instead.
