### ISSUE TITLE
UWP error

### ISSUE THREAD

**Issue by mscrocdile** [IdentityModel/IdentityModel.OidcClient.Samples#30]
I'm getting this error in xamarin forms client using UWP:

{System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at XamKlient.UWP.WabBrowser.<InvokeAsyncCore>d__3.MoveNext()}

It's something wrong with WebAuthenticationBroker?

**Comment by leastprivilege** [comment]
this sample is a contribution from @jasallen - he might be able to help you.

**Comment by jasallen** [comment]
Send me your runtime console output.  You may also need to turn on Oidc client logging.

**Comment by mscrocdile** [comment]
There is
'XamKlient.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
in output of Visual Studio.
How can one turn on Oidc client logging? Is has something to do with options.LoggerFactory? If so, how can one use it?

**Comment by mscrocdile** [comment]
I found that if i connect with uwp client to live https://demo.identityserver.io then everything is ok. So problem is not in client. If i clone demo.identityserver.io and start it then browser in client is open but with the message that i cannot connect to service. 
https://localhost:44300 seems correct in standalone browser. 
I wonder where is the problem..

**Comment by leastprivilege** [comment]
You can't connect to localhost with WAB by default - you can change that:

https://msdn.microsoft.com/en-us/library/windows/desktop/jj658959(v=vs.85).aspx

**Comment by mscrocdile** [comment]
It works. 
Thank you very much

**Comment by mscrocdile** [comment]
Well, it worked until I clicked a Register button. Then I got the message  "We can't connect to the service..." again and in log there is :

AuthHost encountered a navigation error at URL: <https://localhost:44300/Account/Register?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fresponse_type%3Dcode%2520id_token%26nonce%3D20689f6da812e8039b1a0c6bb41742eb%26state%3D4aa992f16617ab75aed53311feeba94b%26code_challenge%3De472PHHSN_ii_yXKCNOQ5XGLJayiHV3QbRVKiYw0x7k%26code_challenge_method%3DS256%26client_id%3Dnative.hybrid%26scope%3Dopenid%2520profile%2520email%2520offline_access%26redirect_uri%3Dxamarinformsclients%253A%252F%252Fcallback> with HttpStatusCode: 404.

Anything with WAB again?

**Comment by mscrocdile** [comment]
With RequireConsent = false it works. I have to study what this parameter means yet. I use IdentityServer4 with Asp.Net identity. Demo.identityServer.io works without this parameter..
