### ISSUE TITLE
Android issue - Xamarin Forms

### ISSUE THREAD

**Issue by mscrocdile** [IdentityModel/IdentityModel.OidcClient.Samples#31]
When I add into empty Xamarin Forms project IdentityModel.OidcClient package and run using Android then project starts, webbrowser is open and app quits and debugger is detached.
If i remove IdentityModel.OidcClient package then MainPage is correctly shown.

**Comment by leastprivilege** [comment]
this sample is a contribution from @jasallen - he might be able to help you.

**Comment by jasallen** [comment]
If you post the android logcat logs, I can try to find something.  

- Also, make sure your Xamarin Forms nuget packages are fully up to date.  
- Try deleting the bin and obj folders for your android project.  
- Do a full rebuild and remove app from target device.  If it's an emulator reset it
- Try targeting a device/emulator that is at least API 25 to make sure it's not a backward compatibility issue.

**Comment by mscrocdile** [comment]
Currently I use API 24 device. I will let you know soon if simulator API 25 helped..

**Comment by thutson** [comment]
Changing the Linker option discussed here fixed similar behavior for me:
[https://forums.xamarin.com/discussion/comment/312645/#Comment_312645](url)
