### ISSUE TITLE
Xamarin Forms- Clean Install JWKS Config Issue

### ISSUE THREAD

**Issue by thutson** [IdentityModel/IdentityModel.OidcClient.Samples#33]
I am implementing OidcClient in a clean Xamarin Forms project but it is throwing an error about a missing parameter in the jwks configuration:

> System.InvalidOperationException: Error loading discovery document: Error connecting to https://demo.identityserver.io/.well-known/openid-configuration/jwks: Value cannot be null.
> Parameter name: method

The sample project runs fine but I can't find what setting is causing the clean install to error on the jwks config? The following log is from the IdentityServer, the first 3 are from the clean install (looking for ~/openid-configuration/jwks while the last three are from the sample calling ~/openid-configuration

![image](https://user-images.githubusercontent.com/4998307/36080544-b22cf2c6-0f5f-11e8-809d-956119c2f9c0.png)

**Comment by rjygraham** [comment]
Did you resolve this? I'm running into the same issue, except it throws in my client application and stops login process.

**Comment by rjygraham** [comment]
Just wanted to report back that I resolved my issue which was caused by linking assemblies in my Android app.

I ended up having to add the following LinkDescription.xml to my project:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<linker>
	<!--<assembly fullname="IdentityModel">
		<type fullname="*"></type>
	</assembly>-->
	<assembly fullname="IdentityModel.OidcClient">
		<type fullname="*"></type>
	</assembly>
	<assembly fullname="Newtonsoft.Json">
		<type fullname="*"></type>
	</assembly>
</linker>
```

More information available here:
https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker

**Comment by ryanmendoza** [comment]
@rjygraham what is your link setting now that you got it working? Don't Link? Link all assemblies?

**Comment by rjygraham** [comment]
Here's where I am right now (this is working). Please note that MyApp.ClientApp is my .NET Core shared Xamarin.Forms assembly and MyApp.ClientApp.Android is my Android app project.

Hope this helps.

`
<?xml version="1.0" encoding="utf-8" ?>
<linker>
	<assembly fullname="MyApp.ClientApp">
		<type fullname="*"></type>
	</assembly>
	<assembly fullname="MyApp.ClientApp.Android">
		<type fullname="*"></type>
	</assembly>
	<assembly fullname="IdentityModel">
		<type fullname="*"></type>
	</assembly>
	<assembly fullname="IdentityModel.OidcClient">
		<type fullname="*"></type>
	</assembly>
		<assembly fullname="Microsoft.IdentityModel.Tokens">
		<type fullname="*"></type>
	</assembly>
	<assembly fullname="Newtonsoft.Json">
		<type fullname="*"></type>
	</assembly>
	<assembly fullname="System.IdentityModel.Tokens.Jwt">
		<type fullname="*"></type>
	</assembly>
</linker>
`

**Comment by ryanmendoza** [comment]
@rjygraham that did it for me. Thanks a ton!

Curious... would explicitly adding these packages (instead of them being installed as dependencies of other packages) via NuGet make this not needed?

**Comment by rjygraham** [comment]
Unfortunately no. The linker basically evaluates code that is explicitly called and builds a dependency graph of types, methods, and properties. Anything it can't determine as being called it'll "throw away." 

Because of the internal workings of the OidcClient, Json.Net, etc using dynamic runtime reflection, the linker cant determine that some types are needed which leads to these errors.

This file is instructing the linker to include everything from the specified assemblies. We could get really surgical and specify specific types instead of * but that would be a time consuming exercise.

Hope that helps. 

Ryan

**Comment by brockallen** [comment]
@thutson does any of this help? or any update from your side?
