### ISSUE TITLE
ChromeCustomTabBrowser doesn't close browser and NOT returning to parent application.

### ISSUE THREAD

**Issue by anvaraj78** [IdentityModel/IdentityModel.OidcClient.Samples#35]
Am building a Xamarin.Android application using ChromeCustomTabBrowser implementation as give in the AndroidClientVS2017 sample project but sample has given StartActivity(getType()) as solution to close/hide the browser.

The StartActivity() creates a new activity, Is there any fix or solution to comeback to the parent activity/application ?

**Comment by brockallen** [comment]
I don't know Android's programming model well enough to answer that. If you find out, let us know -- we'd love to improve the sample. Thanks.

**Comment by leastprivilege** [comment]
closing - feel free to PR when you figure it out

**Comment by tonyyyrocks39** [comment]
Hi,
Are you able to fix this,facing the same problem

**Comment by jrcpereira** [comment]
Did you set **LaunchMode = LaunchMode.SingleTask** on Main Activity?

**Comment by brockallen** [comment]
Where would that be set in here: https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/AndroidClientVS2017/AndroidClient?

**Comment by jrcpereira** [comment]
On MainActivity.cs, like this:
**[Activity(Label = "AndroidClient", MainLauncher = true,  LaunchMode = LaunchMode.SingleTask)]**

The Xamarin Forms sample has this setting on the MainActivity.
I use Xamarin Forms, but this is platform specific.

There are other problems with this custom tabs implementation, such as multiple tasks that are initiated when we click login and close browser multiple times (the close is not handled). When a successful login occurs, multiple tasks return, but only the first return success.

We initially tackled this subscribing to the event **NavigationEvent** from the **CustomTabsActivityManager** but not every browser has the same behaviour. We had to add additional logic to list device available browsers, and if we are comfortable with the default browser, ok, if not we force our option of browser if installed or prompt the user to install it.

I'll try to make a PR on the Xamarin Forms sample next week...

**Comment by brockallen** [comment]
Yea a PR would be great. Thanks

**Comment by softsan** [comment]
In my case when i open the identity login in customtabbrowser and then if i minimize the app it returns "UserCancel" error. In my app i need to switch to another app(e.g. Gmail) to get 4 digit code. So in this case LoginAsync returns error with "UserCancel" so how to solve this?
