### ISSUE TITLE
Question: Logout using default browser

### ISSUE THREAD

**Issue by bdjankowski** [IdentityModel/IdentityModel.OidcClient.Samples#37]
I noticed while utilizing the OidcClient that we can only logout using an embedded browser, while you can login using a default browser (see OidcClient.PrepareLoginAsync) which returns a URL that can then be used in conjunction with a redirect.  So the issue would be to expose the ability to have a "preparelogoutasync" that would return the URL.  

If you call the logout directly, without prepareloginasync, there is additional setup (i.e. ProviderInformation has not been initialized with the client info).

I can implement this and create a pull request, or have you guys work on that addition, or just do it for my application.  I just wanted to get an idea if this is something you're working on, planning on doing, or purposefully decided against.

**Comment by leastprivilege** [comment]
Well I guess we could expose the URL generation for logout and you can invoke any browser you want with that - good enough - or do you have other things in mind?

**Comment by bdjankowski** [comment]
It would be good enough-but I think it could be better and more consistent to have "PrepareLogoutAsync" that returns that URL like PrepareLoginAsync.

**Comment by leastprivilege** [comment]
done

**Comment by brianbarnett316** [comment]
Do you guys have a sample with the PrepareLogoutAsync and the listening to the port for the logout process to determine if the user actually logged out?
