### ISSUE TITLE
Is it possible to set it so it validates ssl certificate by hand?

### ISSUE THREAD

**Issue by sqdavid** [IdentityModel/IdentityModel.OidcClient.Samples#39]
I have an identityserver4 server with a certificate issued by an internal CA.
I cannot install the certificate in all the android devices that connects to my server.

I tried to use a webview (android) and override onReveivedSslError but the code is not executed.

Thanks

**Comment by leastprivilege** [comment]
There's a back-channel handler on the options. This is where you can customize the HTTPS validation parameters.

**Comment by sqdavid** [comment]
Thanks. Found it

**Comment by StephaneMartignier** [comment]
@leastprivilege or @sqdavid 
Can you give an example on how to validate the HTTPS by hand?

When I try to run the UWP sample with my local implementation of IDS4 I've got an exception with "The certificate authority is invalid or incorrect" when calling LoginAsync

Thanks
