### ISSUE TITLE
RefreshToken expiry set to AccessToken expiry

### ISSUE THREAD

**Issue by JonathanReadman** [IdentityModel/IdentityModel.OidcClient.Samples#4]
Using the OidcClient I am attempting to generate a refresh token from my server which is successful but I am never seeing the AbsoluteRefreshTokenLifetime being set. I have also removed my setting of this so it brings through the default value but it is coming back with a value that matches the AccessToken expiry. 

I have added the offline_access scope to be able to use Refresh Tokens.

Below is an example of my client declaration (Some values have been removed):

```
new Client
                {
                    ClientName = "",
                    ClientId = "",
                    
                    Flow = Flows.HybridWithProofKey,

                    ClientSecrets = new List<Secret>
                    {
                        new Secret("".Sha256())
                    },

                    AllowedScopes = new List<string>
                    {
                        Constants.StandardScopes.OpenId,
                        Constants.StandardScopes.OfflineAccess,
                        "VFPToken"
                    },
                    
                    ClientUri = authUri,

                    RequireConsent = true,
                    AllowRememberConsent = false,

                    RedirectUris = new List<string>
                    {
                        "",
                    },

                    AccessTokenLifetime = 1200,

                    AbsoluteRefreshTokenLifetime = 5184000,
                    RefreshTokenExpiration = TokenExpiration.Absolute,
                }
            };
```
Below is an example of configuring OidcClient

```
var authority = Configuration.Instance.AuthURI + "identity";

            var options = new OidcClientOptions(
                authority,
                clientId,
                clientSecret,
                "openid offline_access VFPToken",
                redirectUri,
                new WinFormsWebView());

            options.UseFormPost = true;
            _oidcClient = new OidcClient(options);
```

Below is trying to get the refresh token

```
var result = await _oidcClient.LoginAsync(trySilent: false);
                var refreshToken = await _oidcClient.RefreshTokenAsync(result.RefreshToken);
```

refreshToken always has an expiry that matches the AccessToken expiry.

I have checked my logs (Attached) and can see the Lifetime value of the issues refresh token being the default value from my server.

Am I missing something in my OidcClient or is this an issue?
[logSnippet.txt](https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/files/413335/logSnippet.txt)

**Comment by leastprivilege** [comment]
I am not sure I follow...is this an OidcClient issue - or an identityserver issue?

**Comment by JonathanReadman** [comment]
I'm asking the question if the issue is with OidcClient

My example shows the client I have configured to have a refresh token with a lifetime of 5184000. When I inspect the refresh token I get back from performing a login with OidcClient my refresh token lifetime is set to 1200. I obviously want to store the refresh token but I want it to be valid for the length of time I specified in the IdentityServer client declaration.

**Comment by leastprivilege** [comment]
Where do you see a refresh token lifetime? The token response only contains the access token lifetime.

**Comment by JonathanReadman** [comment]
Refresh token lifetime within the refreshToken variable here using the result.RefreshToken from the response returned from the OidcClient LoginAsync

var result = await _oidcClient.LoginAsync(trySilent: false);
var refreshToken = await _oidcClient.RefreshTokenAsync(result.RefreshToken);

**Comment by leastprivilege** [comment]
That's the access token lifetime - not the refresh token.

**Comment by JonathanReadman** [comment]
I would have expected that the following returns the details about a refresh token?

public Task<RefreshTokenResult> RefreshTokenAsync(string refreshToken);

Is there a method available on the OidcClient that allows me to get a refresh token object so I can store this locally on my client?

My goal is to prevent the user from having to login repeatably by using the refresh token to generate a new access token when that expires.

**Comment by leastprivilege** [comment]
You get back the refresh token - and that's what you store in the client.

But OAuth does not return the refresh token lifetime - as per spec.

**Comment by LaurenceSkoropinski** [comment]
Following on from this, we have a refresh token, and we need to get a new access token, google searchers suggest using TokenClient with url set to token_endpoint passing also clientid, clientsecret. Then use the RequestRefreshTokenAsync method passing the refresh token. This does return an access token, but I was expecting the refresh token to be returned unchanged, unfortunately it returns a new Refresh token. Is this to be expected, or is there another way to keep the refresh token unchanged(if not expired) and get a new access token from the refresh token. Have googled but have not found anything of value.

**Comment by leastprivilege** [comment]
new question - new issue. Also again - this is an identityserver question.

**Comment by Sathiyamm** [comment]
@leastprivilege  
Hi, i'm got new access code using refresh code. That time refresh code gets in null in new token response.Is it correct?
And one more time RefreshAccessToken method call in same refresh code using that time I'm getting Error = "invalid_grant".
Is it correct or any mistakes in doing?

 ```
public async Task<IActionResult> RefreshAccessToken(string refreshToken,string accessToken)
        {
            try
            {
                var identityService = await DiscoveryClient.GetAsync("http://localhost:5000");
                // request token
                var tokenClient = new TokenClient(identityService.TokenEndpoint, "client", "secret");
                var tokenResponse = await tokenClient.RequestRefreshTokenAsync(refreshToken);                     
                return Ok(new { success = true, tokenResponse = tokenResponse });
            }
            catch (Exception ex)
            {
                logger.Error(ex, ex.Message);
                return Ok(new { success = false, data = string.Empty, message = ex.Message });
            }
        }
```
