### ISSUE TITLE
WinFormsWebView Persist Token

### ISSUE THREAD

**Issue by stumpykilo** [IdentityModel/IdentityModel.OidcClient.Samples#41]
What is the strategy for persisting the LoginResult (or some of its properties) and then initializing the HttpClient with the RefreshTokenHandler upon opening a WinForms app? I don't want my users to have to LoginAsync and get a new token everytime they open an app. Can someone point me to an example of this being done or give me some guidance on this?

**Comment by mkreuzmayr** [comment]
@leastprivilege currently having the same problem, is this still the recommended way?

I have implemented a sample where I log in via the `OidcClient.PrepareLoginAsync` login request (with scope `offline_access`) when I get the refresh token back I save it straight to the Windows Credentails Manager. Then I create my session object with the `LoginResult`.

When the app starts again I try to read the refresh token from the Windows Credentails Manager, if it exists i refresh the access token via `OidcClient.RefreshTokenAsync` get the user info via `GetUserInfoAsync` and recreate my session object.
