### ISSUE TITLE
Issue with EmbeddedBrowser

### ISSUE THREAD

**Issue by amitt0488** [IdentityModel/IdentityModel.OidcClient.Samples#45]
I am using the code for ExtendedBrowser, it is working fine when we call this function from within the window form Button click event
 var result = await _oidcClient.LoginAsync(DisplayMode.Visible); 
and launches the browser

But, when i moved this code to a different layer, then i am getting this exception 

ActiveX control '8856f961-340a-11d0-a96b-00c04fd705a2' cannot be instantiated because the current thread is not in a single-threaded apartment. 

public LoginResult TestOIDCAuthenticationUsingEmbeddedBrowser(OidcClientOptions oidcClientOptions)
        {
            var oidcClient = new OidcClient(oidcClientOptions);

            //return oidcClient.LoginAsync(DisplayMode.Visible).Result;
            Task<LoginResult> task = Task.Run<LoginResult>(async () => await oidcClient.LoginAsync(DisplayMode.Visible));

            return task.Result;
        }

This exception is occurring at:

using (var browser = new CustomEmbeddedBrowser()
                {
                    Dock = DockStyle.Fill
                })

To fix it, i set the thread in apartment mode:

public async Task<BrowserResult> InvokeAsync(BrowserOptions options)
        {
            //return LaunchBrowser(options).Result;

            BrowserResult result = null;
            Thread thread = new Thread(() =>
            {
                try
                {
                    LaunchBrowser(options);
                }
                catch (Exception ex)
                {

                }
            });
            thread.Name = "BrowserLaunchThread";
            thread.SetApartmentState(ApartmentState.STA);
            thread.Start();
            thread.Join();

            return result;
        }

Doing this, invoked a new window, but nothing is getting rendered and the screen gets hanged.
May be some deadlock is created.
Can anyone help me with it.

Thanks
Amit

**Comment by leastprivilege** [comment]
Sorry - don't know the answer. Hope you got it resolved somehow.

**Comment by gjvdkamp** [comment]
Hi Amit, I'm runnign into the same issue, did you ever find a solution to this?

**Comment by arooran** [comment]
@gjvdkamp I had a similier issue like @amitt0488 mentioned. I have used a TaskScheduler to overcome that issue. Please refer this stackoverflow article for creating [https://stackoverflow.com/questions/21790151/calling-method-on-correct-thread-when-control-is-created-in-new-thread/21808747#21808747](url) winform controls in STA.

This is my implementation for ActiveX control issue.
`    public async Task<BrowserResult> InvokeAsync(BrowserOptions options)
        {
            using (var apartment = new MessageLoopApartment()) {

                return await apartment.Invoke(() => LaunchBrowser(options));

            }        
        }`

Hope this will help for your issue.
