### ISSUE TITLE
Xamarin Form Sample for iOS does not rederict to app after succesful login

### ISSUE THREAD

**Issue by yalexopoulosQ** [IdentityModel/IdentityModel.OidcClient.Samples#47]
Cannot redirect back to application after successful login. ios 11.4 @jasallen

**Comment by pakbaz** [comment]
same issue with iOS 12

**Comment by alapointe42** [comment]
I also have this issuie, the sample is ok with iOS 12, but it's using the hybrid flow, the issue seems to be only with "AuthenticationFlow.AuthorizationCode".

**Comment by leastprivilege** [comment]
@jasallen is maintaining this sample. Don't know anything about Xamarin Forms.

**Comment by javaadpatel** [comment]
Did anyone figure out what the cause of this is?

**Comment by ryanbuening** [comment]
I just noticed this issue after I opened #60 . Has anyone been able to resolve this? Are you getting an error: "Safari cannot open the page because the address is invalid." or a different error?

**Comment by jrcpereira** [comment]
I can confirm that this is working with Xamarin Forms on iOS up to v12.

Did you configured the CFBundleURLSchemes on info.plist on the iOS project (https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/XamarinForms/XamarinFormsClient/XamarinFormsClient.iOS/Info.plist)?

Did you configured the redirect url for that client on Identity server and used the same path while requesting login?

**Comment by ryanbuening** [comment]
@jrcpereira that was my issue. Thanks!
