### ISSUE TITLE
Upgrading Xamarin Forms to latest stable results in Context being null

### ISSUE THREAD

**Issue by JohnGalt1717** [IdentityModel/IdentityModel.OidcClient.Samples#49]
If you update all modules to the latest Xamarin forms and libraries and fix the project to not specify version 8, and get the latest of these libraries as well from nuget and run the sample, then line 30 of ChromCustomTabsBrowser will have a null _context.

Is there a work around?

**Comment by leastprivilege** [comment]
This sample is a contribution from Jason DeBoever (@jasallen) - please contact him (or mention him) if there are any issues.

**Comment by allistoncarlos** [comment]
I'm having the same issue... please @jasallen, let us know if there's a way to make it work with the latest Forms version

**Comment by allistoncarlos** [comment]
I've managed to make it work! The problem was occurring because of CrossCurrentActivity.Current.Activity coming null... All we needed to do was init it in MainActivity.cs

``` csharp
protected override void OnCreate(Bundle bundle)
{
    CrossCurrentActivity.Current.Init(this, bundle);
    DependencyService.Register<ChromeCustomTabsBrowser>();
    ...
}

**Comment by brockallen** [comment]
Which sample @allistoncarlos? Could you suggest a PR?

**Comment by allistoncarlos** [comment]
Sure @brockallen! I've corrected it in my Xamarin Forms project, but I can replicate it in the sample and send the PR.
