### ISSUE TITLE
xamarin.forms' Android Press device's back button return to login button page(new app instance)

### ISSUE THREAD

**Issue by jingliancui** [IdentityModel/IdentityModel.OidcClient.Samples#52]
1. The app have the LoginPage and the MainPage , Login Page has a LoginButton,clicked the loginbutton.Trigger the `client.LoginAsync()` method.

2. App will trigger the `OnSleep()` 

3. User do login operate in the web(ChromeCustomTabsBrowser),and login succeed 

4. ChromeCustomTabsBrowser send redirecturl to the CallbackActivity which trigger 
`StartActivity(typeof(MainActivity));` MainActivity will trigger the `new app`.

5. Then app now has the loginresult then it go to the Mainpage.

6. Click the device's back button,the new app instance will trigger the onsleep

7. the fist app instance trigger the `OnResume`

8. Result is go to the LoginPage (first instance's loginpage)

So can you provider some suggestion for me to deal the `4 step above` ?

**Comment by jingliancui** [comment]
Seem like that I forgot add this code to the MainActivity
`LaunchMode = Android.Content.PM.LaunchMode.SingleTask`

**Comment by mattmiley** [comment]
Wow, I did the same thing. Thanks for this @jingliancui

**Comment by jingliancui** [comment]
you are welcome  : )
