### ISSUE TITLE
What is the difference between three android sample apps: AndroidClientChromeCustomTabs, AndroidClientVS2017 and AndroidClientWebView

### ISSUE THREAD

**Issue by PingPongSet** [IdentityModel/IdentityModel.OidcClient.Samples#53]
I need to integrate single sign in/out with Xamarin Android and IdentityServer4 via ASP.NET Core.

The sign in/out of the Xamarin Android app is used for company employee only, not like Google etc. 

Which sample apps below are close to my scenario?

AndroidClientChromeCustomTabs
AndroidClientVS2017
AndroidClientWebView

**Comment by leastprivilege** [comment]
They use different styles of hosting the browser. The most recommended one is the Chrome custom tab.

**Comment by PingPongSet** [comment]
@leastprivilege 

This repo of examples is a good starting point.

I wonder if there are document on these samples, which explains what each method do, or document for integrating IndentityServer4 with Xamarin Android. I cannot see any good document on these area on the web.

**Comment by PingPongSet** [comment]
Does AndroidClientChromeCustomTabs require Chrom browser installed on the device?

**Comment by PingPongSet** [comment]
Do you mean all three samples require a browser installed? Is it Chrome browser?

Is it possible to use Xamarin Android UI control instead for user name and passoworsd, ie the login page.

**Comment by leastprivilege** [comment]
You can use whatever browser you want by implementing IBrowser. I don't use Android, so I don't know the platform specifics.
