### ISSUE TITLE
Login via Xamarin Android UI instead of server side login page, IdentityServer4, ASP.NET CORE

### ISSUE THREAD

**Issue by PingPongSet** [IdentityModel/IdentityModel.OidcClient.Samples#56]
I wonder if it is possible to use Xamarin Android UI as a login page instead of getting directed to server side login page, which allows the mobile app to authenticate users by communicating with server side behind the scenes.

The reason is that we want to avoid the redirecting from mobile to server side, and back to mobile app.

Can anyone provide links on how to implement this case in single sign on?

**Comment by PingPongSet** [comment]
@jrcpereira 

This is helpful. 

Do you have links on why it is not recommended? Is it because of security concern or something else? 

The username and password is provided by user via Android UI using TLS1.2. It should be secure. 

Apart from this repo, where or which forum can I post this question? 

Stackoverflow.com is code only, cannot be discussed, which is useless nowaday.

**Comment by leastprivilege** [comment]
Technically it is totally possible. But read this first

https://tools.ietf.org/html/rfc8252
