### ISSUE TITLE
Facebook Xamarin

### ISSUE THREAD

**Issue by travisjs** [IdentityModel/IdentityModel.OidcClient.Samples#57]
Has anybody successfully used IdentityModel.OidcClient with Facebook?

I've tried several different endpoints, but I usually get this error: "Error loading discovery document: Error connecting to https://m.facebook.com/dialog/oauth/.well-known/openid-configuration: '"utf-8"' is not a supported encoding name."

           var browser = new SFAuthenticationSessionBrowser();
           var options = new OidcClientOptions
            {
                Authority = "https://m.facebook.com/dialog/oauth/",
                ClientId = "xyz",
                Scope = "",
                RedirectUri = "xamarinformsclients://callback",
                Browser = browser,

                ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect
            };

**Comment by leastprivilege** [comment]
AFAIK Facebook does not support OpenID Connect - they're evil.
