### ISSUE TITLE
WinForms Logout

### ISSUE THREAD

**Issue by marktsoper** [IdentityModel/IdentityModel.OidcClient.Samples#58]
The WinFormsWebView Sample LogoutButton is commented out.   I tried to remove commented out code and it would not logout.  The XamarinForms logout works.

  private async void LogoutButton_Click(object sender, EventArgs e)
        {
            //await _oidcClient.LogoutAsync(trySilent: Silent.Checked);
            //AccessTokenDisplay.Clear();
            //OtherDataDisplay.Clear();
        }

**Comment by markns** [comment]
I can confirm this also. 

After uncommenting the code in `LogoutButton_Click` the following exception is thrown by `browser.Navigate(options.StartUrl);`
```
Exception thrown: 'System.UriFormatException' in System.dll
```

**Comment by marktsoper** [comment]
I ended up hacking it up a bit and got a workaround.  

Can not remember where I found this solution but has worked.

Logout Button 
{

 WinInetHelper.SupressCookiePersist();

}

    public static class WinInetHelper
    {
        public static bool SupressCookiePersist()
        {
            // 3 = INTERNET_SUPPRESS_COOKIE_PERSIST 
            // 81 = INTERNET_OPTION_SUPPRESS_BEHAVIOR
            return SetOption(81, 3);
        }

        public static bool EndBrowserSession()
        {
            // 42 = INTERNET_OPTION_END_BROWSER_SESSION 
            return SetOption(42, null);
        }

        static bool SetOption(int settingCode, int? option)
        {
            IntPtr optionPtr = IntPtr.Zero;
            int size = 0;
            if (option.HasValue)
            {
                size = sizeof(int);
                optionPtr = Marshal.AllocCoTaskMem(size);
                Marshal.WriteInt32(optionPtr, option.Value);
            }

            bool success = InternetSetOption(0, settingCode, optionPtr, size);

            if (optionPtr != IntPtr.Zero) Marshal.Release(optionPtr);
            return success;
        }

        [DllImport("wininet.dll", CharSet = CharSet.Auto, SetLastError = true)]
        private static extern bool InternetSetOption(
            int hInternet,
            int dwOption,
            IntPtr lpBuffer,
            int dwBufferLength
        );
    }

**Comment by markns** [comment]
@marktsoper  Thanks very much for the code snippet, but unfortunately it doesn't seem to make any difference for me. Do you remember if was the same `UriFormatException` on `Navigate` you were getting?
