### ISSUE TITLE
Tokenvalidator ValidateAsync returning JosePCL.Jwt.Verify(): Invalid signature.

### ISSUE THREAD

**Issue by pottabathini** [IdentityModel/IdentityModel.OidcClient.Samples#6]
we are trying identitymodel OpenID and OAuth in the desktop application. Using identitymodel oidcclient object loginasync method we able to open the webview and login successfully.

After login, data got returned to the application and application able to decode the form data into a string. When it is trying to validate the returned data application giving an error like "JosePCL.Jwt.Verify(): Invalid signature.".

We debug further and able to identify the root cause. Because of my STS provider not have the end point for "connect/identitytokenvalidation", Identitymodel returning a generic error.

As per the article https://identityserver.github.io/Documentation/docsv2/endpoints/identityTokenValidation.html that endpoint is mandatory to get the claims.

But same claims already coming in the response body of id_token(JWT token) parameter, can we return those claims instead of calling another endpoint API?

Is there any option to make validation optional/ add custom validation?

**Comment by leastprivilege** [comment]
I really don't want to annoy you - but why is that an issue with the sample? Wouldn't that rather be an issue for the actual library??

Anyways - i think you are confused - the default validator is not using the token validation endpoint. It is using JosePCL - and that's what you exception confirms.

Focus on the DefaultIdentityTokenValidator - and report your finding in the main repo.
