### ISSUE TITLE
SFAuthenticationSession deprecated

### ISSUE THREAD

**Issue by ryanbuening** [IdentityModel/IdentityModel.OidcClient.Samples#62]
[SFAuthenticationSession ](https://developer.apple.com/documentation/safariservices/sfauthenticationsession)has been deprecated and Apple reports to use [ASWebAuthenticationSession ](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession)instead.

SFAuthenticationSession is being used in the XamarinForms sample [here](https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/XamarinForms/XamarinFormsClient/XamarinFormsClient.iOS/SFAuthenticationSessionBrowser.cs).

**Comment by jrcpereira** [comment]
Submitted [PR #63](https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/pull/63) to update the sample.

**Comment by leastprivilege** [comment]
merged. thanks!
