### ISSUE TITLE
Does  IdentityModel.OidcClient support Silent login ?

### ISSUE THREAD

**Issue by PrachiKarapurkar** [IdentityModel/IdentityModel.OidcClient.Samples#64]
Hi, 
I wanted to know how we can implement **Silent login** with **IdentityModel.OidcClient** for android and iOS applications ?

Thanks in advance

**Comment by leastprivilege** [comment]
What's a silent login?

**Comment by PrachiKarapurkar** [comment]
> What's a silent login? 
Thanks for quick reply.
Basically, **Silent login** allows user to login without any user interaction.

After registering the user on Identity server, I want to login him/her to the application without having the user to log into the application again via login screen. 

How can we handle it with  IdentityModel.OidcClient ?

Thanks in advance

**Comment by leastprivilege** [comment]
And how does the user enter credentials?

**Comment by PrachiKarapurkar** [comment]
> And how does the user enter credentials?

User is already logged in browser. What I am trying to replicate is web authorisation flow with prompt = none

**Comment by leastprivilege** [comment]
Well - you can start the system browser. If the user is already signed-in, it will get SSO - and with prompt=none you will get back an error I guess.

Never tried it.

**Comment by PrachiKarapurkar** [comment]
Is there any way to set **RequirePkce = true** on Android and iOS app in **OidcClientOptions** ?

**Comment by leastprivilege** [comment]
OidcClient always does PKCE.
