### ISSUE TITLE
Winforms: Canceling demo server login pops up shell browser

### ISSUE THREAD

**Issue by natelaff** [IdentityModel/IdentityModel.OidcClient.Samples#65]
Configure WinFormsSample to point to demo.identityserver.io and log in. If you cancel here, you get the access_denied error, but then Windows opens a shell browser to the authorization end point.

Is there a way to fix this?

**Comment by leastprivilege** [comment]
Never saw that before.

**Comment by natelaff** [comment]
I usually don't have a cancel button, so I've never noticed it, but decided to use the QuickStart to get some IS4 goodness that I didn't previously have.

I have seen a similar issue one other time where after a successful Facebook login via external providers, a blank tab would open in shell for FB.

**Comment by natelaff** [comment]
This also happens if you deny consent I just realized as well. Have not yet been able to find a cause, of course I don't know the internals of this as well.
