### ISSUE TITLE
How to register and login with identity

### ISSUE THREAD

**Issue by PrachiKarapurkar** [IdentityModel/IdentityModel.OidcClient.Samples#67]
How to sign in and sign up user with oidc on xamarin android and iOS?
Below is my code for login on android
 ```
    var options = new OidcClientOptions
            {
                Authority = authority,
                ClientId = "native.hybrid",
                ClientSecret = "xoxo",
                Scope = "openid profile api",
                RedirectUri = "io.identitymodel.native://callback",
                ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect,
                Browser = new ChromeCustomTabsWebView(this)
            };

            _oidcClient = new OidcClient(options);
            var result = await _oidcClient.LoginAsync();

```
How can I use same method to register?

Thanks in advance

**Comment by leastprivilege** [comment]
OidcClient is a protocol library. This is beyond the protocol but custom application logic on your side.

**Comment by PrachiKarapurkar** [comment]
> OidcClient is a protocol library. This is beyond the protocol but custom application logic on your side.

Is there any events shown below which we can use 
options.Events = new OpenIdConnectEvents
                {
                    OnRedirectToIdentityProvider = (ctx) =>
                    {
                        if (ctx.Properties.RedirectUri.Contains("UserInfo"))
                        {
                            ctx.ProtocolMessage.Parameters.Add("button", "login");
                        }
                        else
                        {
                            ctx.ProtocolMessage.Parameters.Add("button", "register");
                        }
                        return Task.CompletedTask;
                    }
                };
