### ISSUE TITLE
Reference to wrong `result` in NetCoreConsoleClient

### ISSUE THREAD

**Issue by Scuzzlebuttt** [IdentityModel/IdentityModel.OidcClient.Samples#68]
I think this should be `refreshResult` not `result`.

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/d4427d4cbef1b20833661f856c947007cc98ba00/NetCoreConsoleClient/src/NetCoreConsoleClient/Program.cs#L105

And right below that, I think these should be `refreshResult` as well:

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/d4427d4cbef1b20833661f856c947007cc98ba00/NetCoreConsoleClient/src/NetCoreConsoleClient/Program.cs#L115-L116

**Comment by leastprivilege** [comment]
thanks!

**Comment by leastprivilege** [comment]
Please send a PR.

**Comment by Scuzzlebuttt** [comment]
I think I did it right...

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/pull/74

**Comment by leastprivilege** [comment]
thanks!
