### ISSUE TITLE
Update to AndroidClientWebView

### ISSUE THREAD

**Issue by ChrisTowles** [IdentityModel/IdentityModel.OidcClient.Samples#7]
Creating an Issue to Include with a pull request with some updates for the AndroidClientWebView Client.

- Update several Nuget Packages
- Update Example Client configuration for IdentityServer4
- UI Buttons to Trigger Logon

**Comment by MrXemiu** [comment]
Just want to thank you for the update, your forked branch is very helpful  👍

**Comment by leastprivilege** [comment]
What happened to your updates - since I am not doing any Android development - could you update the samples to the lastest v2?
