### ISSUE TITLE
WinFormsWebView Sample - 404 error when using bob/bob

### ISSUE THREAD

**Issue by dchwartz-optimal** [IdentityModel/IdentityModel.OidcClient.Samples#71]
I downloaded the sample application from my account dashboard.  When running it, I encountered two issues:
1) When I log in with alice/alice, I get back a 404 exception on this URL
GET localhost/winforms.client?code=h9ThlU3UwpS8oCgEL7oKqXYzgKq9bkUjUCXlPYyhlnI&scope=openid%20email%20api%20offline_access&state=JOjiZ7JPsAEN_OsoEyFjJg&session_state=FJPHt0kL9EzyeiDH_aeiciBOUu3CH--ZKAJ6ukcBF80.HAVu-r9dh4ZcrxE1RO_0zA HTTP/1.1

2) When I try google authentication, it fails on a "script error" in the browser in two places... and then the Allow button is disabled.

Before selecting an account: 
https://ssl.gstatic.com/accounts/static/_/js/k=gaia.gaiafe_signin.en.BmFz2BdblVA.O/am=AwAAAAAAAAAAAAYX/d=1/ct=zgms/rs=ABkqax2gCAa1apDA-ZuSMgGLhnbbXO5Now/m=signin_chooseaccount,signin_botguard

On permissions page:
https://accounts.google.com/signin/oauth/legacy/consent?authuser=0&part=AJi8hAOlZv4RivBnICg4aCB92ErHiHKiQF5FmQvqYvS_-x7IIBhqj0opNn-1zCweTUHzX1js_G45IIIkxNl29f7Wvcmfy5HJmvS6iqGa9fwbRg6FbsaAqDxx6ye-R4by1Cyb2DqPAnlZ95M70t9i5R7MXFhEAKBExq0PIBDQ43encAtmc4duVx7ES-aO_wUvtRHol3ebU52UfX0w61lRhaSPzfkHy3t9yCpq9lx_Ool4zTwV7Mn-me9L2djCd6MIKmnnEZNrE139OTAjjD-j7BV4ntwGYAW5GpxL_nC1kMRBV-x20-rPD6npLxe-ZQwM0fpvbyHPMAkaL2EHahaVP2FMRWgd10OiGTr0z-iLumP0_SaZeeIrzyme8R_fy_SpUtXIFlxaNKo_OaVpgqHaG1wH8ADKJZQuob3m7zqVtGxJqw8d9NVyLLCO2q56UmJt9sDQmyHbwf7y&as=aqzCeVCkWUvdO5Gh8ksvkA&pli=1
Can anyone help?

David

**Comment by natrajsr** [comment]
I am also facing this issue. Please help.

**Comment by natrajsr** [comment]
I have given my solution as pull request by handling in WinFormsWebView. It works for me now.

**Comment by leastprivilege** [comment]
I just merged the PR. Works fine.
