### ISSUE TITLE
Xamarin.Forms - how to cancel await when external browser is closed (login cancelled)?

### ISSUE THREAD

**Issue by peter-raehse** [IdentityModel/IdentityModel.OidcClient.Samples#75]
I have a question regarding log-in and log-out scenario in Xamarin.Forms with the ChromeCustomTabsBrowser (Android).

When I start authentication with 
`var authResult = await _client.LoginAsync(new LoginRequest());`
and the users taps on the close icon in the browser, the callback never gets called and the task will never return.

Is there any way to cancel the await _client.LoginAsync when the user closes the browser?
Thank you very much in advance!

**Comment by jrcpereira** [comment]
Hi!

Yes, you can register for the browser Navigation Events and handle the cancel button.
There are other things you must take in account, because not every browsers implement navigation events (like Firefox for Android), neither all browsers handle events the same way (like the Samsung browser), but at least almost every browser support custom tabs...

Neverthless, here is a quick fix for what you want:

On `ChromeCustomTabsBrowser` class, add the event to the `CustomTabsActivityManager`

`_manager.NavigationEvent += _manager_NavigationEvent;`

My event handler is as follow:

```
private int _previousNavigationEvent = 0;
private void _manager_NavigationEvent(int navigationEvent, Bundle extras)
{
      switch (navigationEvent)
      {
             case CustomTabsCallback.TabHidden:
             {
                 //Chrome throws NavigationAborted before TabHidden when redirecting. When Tab is hidden, the task IS ALREADY completed!
                 //SBrowser throws NavigationFailed before TabHidden when redirecting. When Tab is hidden, the task IS NOT YET completed...
                if (_previousNavigationEvent != CustomTabsCallback.NavigationFailed && _previousNavigationEvent != CustomTabsCallback.NavigationAborted)
                {
                       OidcCallbackActivity.Callbacks -= _callback;
                       if (_task != null && !_task.Task.IsCompleted)
                       {
                            _task.TrySetResult(new BrowserResult
                            {
                                ResultType = BrowserResultType.UserCancel
                            });
                       }
                  }
                  break;
           }
     }

     _previousNavigationEvent = navigationEvent;
}
```

When executing login you can check for UserCancel event as following:

```
 if (loginResult.IsError &&  loginResult.Error == BrowserResultType.UserCancel.ToString())
```

Please, adapt the code as you wish.

I did implement some aditional things, such as identifying the device default browser, and if it doesn't support what I wish, I just force Chrome or other browser I wish.

**Comment by peter-raehse** [comment]
Excellent, thanks a lot! I will try this.

**Comment by peter-raehse** [comment]
I tried this now. It seems that the ManagerNavigationEvent is never been hit.
I subscribe to the event like this:
```
        public ChromeCustomTabsBrowser(Activity context)
        {
            _context = context;
            _manager = new CustomTabsActivityManager(_context);
            _manager.NavigationEvent += ManagerNavigationEvent;
        }
```
But the `ManagerNavigationEvent` never catches an event.
The biggest change to "one year ago" might be Android 10 and the AndroidX support libraries.

**Comment by jrcpereira** [comment]
I forgot to mention that you also need to bind the browser to be used to the manager, before subscribing to the event.

```
...
_manager = new CustomTabsActivityManager(_context);
_manager.BindService();
_manager.NavigationEvent += ManagerNavigationEvent;
```

If you wish to force a browser to perform the authentication, just do this:
```
_manager = CustomTabsActivityManager.From(_context, _packageName);
_manager.BindService(_packageName);
``` 
where the `_packageName` is the full browser app name (for Chrome is "com.android.chrome")

I am using Android 10 and the AndroidX libraries in my projects and it works just fine.

When I said some things may have changed, I was talking about more browsers supporting CustomTabs and events or behaviours changing.
Seems like Firefox haven't implemented events yet (https://github.com/mozilla-mobile/focus-android/issues/2183).

**Comment by peter-raehse** [comment]
Thanks a lot! That was the missing part. Now it's working great. A very good solution.

**Comment by softsan** [comment]
I've a problem when user navigates to another app then identity tab is closed(hidden). In my case, we have a login with email which send them 4 digit code in email. So now if user moves to another app(e.g. Gmail) to get the code, the identity chrome tab is closed. So is there anyway we can keep that chrome tab visible until the user close it explicitly or by pressing login inside the identity web page ?

**Comment by enantiomer2000** [comment]
> I forgot to mention that you also need to bind the browser to be used to the manager, before subscribing to the event.
> 
> ```
> ...
> _manager = new CustomTabsActivityManager(_context);
> _manager.BindService();
> _manager.NavigationEvent += ManagerNavigationEvent;
> ```
> 
> If you wish to force a browser to perform the authentication, just do this:
> 
> ```
> _manager = CustomTabsActivityManager.From(_context, _packageName);
> _manager.BindService(_packageName);
> ```
> 
> where the `_packageName` is the full browser app name, like "com.android.chrome" for Chrome.
> 
> I am using Android 10 and the AndroidX libraries in my projects and it works just fine.
> 
> When I said some things may have changed, I was talking about more browsers supporting CustomTabs and events or behaviours changing. Seems like Firefox haven't implemented events yet ([mozilla-mobile/focus-android#2183](https://github.com/mozilla-mobile/focus-android/issues/2183)).

I have tried this code in my project to but cancelling the login doesn't call NavigationEvent. Not sure what I am doing wrong as there doesn't seem to be any documentation on this. Could somebody provide a complete class for reference?  For reference, below is my class code which is not working properly:

`
public class ChromeCustomTabsBrowser : IBrowser
    {
        private readonly Activity _context;
        private readonly CustomTabsActivityManager _manager;
        Action<string> _callback;
        TaskCompletionSource<BrowserResult> _task;
        public ChromeCustomTabsBrowser() : this(CrossCurrentActivity.Current.Activity) { }


        public ChromeCustomTabsBrowser(Activity context)
        {
            _context = context;
            _manager = new CustomTabsActivityManager(_context);

            _manager.BindService();
            _manager.NavigationEvent += ManagerNavigationEvent;
        }

        private int _previousNavigationEvent = 0;
        private void ManagerNavigationEvent(int navigationEvent, Bundle extras)
        {
            switch (navigationEvent)
            {
                case CustomTabsCallback.TabHidden:
                    {
                        //Chrome throws NavigationAborted before TabHidden when redirecting. When Tab is hidden, the task IS ALREADY completed!
                        //SBrowser throws NavigationFailed before TabHidden when redirecting. When Tab is hidden, the task IS NOT YET completed...
                        if (_previousNavigationEvent != CustomTabsCallback.NavigationFailed && _previousNavigationEvent != CustomTabsCallback.NavigationAborted)
                        {
                            OidcCallbackActivity.Callbacks -= _callback;
                            if (_task != null && !_task.Task.IsCompleted)
                            {
                                _task.TrySetResult(new BrowserResult
                                {
                                    ResultType = BrowserResultType.UserCancel
                                });
                            }
                        }
                        break;
                    }
            }

            _previousNavigationEvent = navigationEvent;
        }

        public Task<BrowserResult> InvokeAsync(BrowserOptions options, CancellationToken cancellationToken = default)
        {
            _task = new TaskCompletionSource<BrowserResult>();
                
            var builder = new CustomTabsIntent.Builder(_manager.Session)
               .SetToolbarColor(Color.Argb(255, 52, 152, 219))
               .SetShowTitle(true)
               .EnableUrlBarHiding();

            var customTabsIntent = builder.Build();

            // ensures the intent is not kept in the history stack, which makes
            // sure navigating away from it will close it
            customTabsIntent.Intent.AddFlags(ActivityFlags.NoHistory);

            _callback = null;
            _callback = url =>
            {
                OidcCallbackActivity.Callbacks -= _callback;

                _task.SetResult(new BrowserResult()
                {
                    Response = url
                });
            };

            OidcCallbackActivity.Callbacks += _callback;

            customTabsIntent.LaunchUrl(_context, Android.Net.Uri.Parse(options.StartUrl));

            return _task.Task;
        }
    }
`
