### ISSUE TITLE
ASP.NET Framework Example

### ISSUE THREAD

**Issue by joshbinney** [IdentityModel/IdentityModel.OidcClient.Samples#76]
Hey there. Had success with the quickstart client with UI for .NET Core, it's working great! My end goal however is to get this working with ASP.NET Framework as I have an older server I want to connect and authenticate with IdentityServer4. I have tried using the old IdentityServer3 samples with no luck, and I'm not sure if the issues I faced were due to Client-side configurations or Identity Server configurations. A .NET Framework example that could take the place of the .NET Core example from the 3rd Quickstart article would be amazing, as I would not have to worry about the issue being on the Identity Server end, and could see a correctly working example of authentication in a similar system to my own. 

Cheers!

**Comment by juanan** [comment]
It would be great for me and ASP.NET Framework as well or some guidance instead.

**Comment by leastprivilege** [comment]
OidcClient is a for native front-end apps. Not web applications.
