### ISSUE TITLE
Bug in Logout XamarinForms sample

### ISSUE THREAD

**Issue by vdecristofaro** [IdentityModel/IdentityModel.OidcClient.Samples#79]
Added Logout code to the Xamarin Forms sample available [here](https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/XamarinForms).
Now, like it happens on login, even in logout mode a screen like this one 
<img width="276" alt="image" src="https://user-images.githubusercontent.com/18700475/83703549-3eb5a280-a610-11ea-8821-82e5daacce82.png">
is showed before logout.

### Issue / Steps to reproduce the problem
All the changes are in the `MainPage.xaml` and `MainPage.xaml.cs`

`MainPage.xaml`

1. Just  after the "Call Api" button add a button for logout

`
     <Button Text="Logout" x:Name="Logout" Padding="20" />
`

`MainPage.xaml.cs`

1. Add two additional private class level variables like this

```
        LogoutResult _logoutResult;
        private string _identityToken = string.Empty
``` 

2. Wire up a new event handler for logout button in class constructor

`
      Logout.Clicked += Logout_Clicked;
`

3. Implement the event handler 

```
    private async void Logout_Clicked( object sender, EventArgs e ) {
        var logoutRequest = new LogoutRequest() {
            IdTokenHint = _identityToken
        };
        _logoutResult = await _client.LogoutAsync( logoutRequest );
    }
```

4. In Login_Clicked save the received identity token in class variable

```
    _identityToken = _result.IdentityToken;
```

5. Run the sample, login with alice/alice, then try  to logout.  

@jrcpereira 
I have seen you did the new browser implementation, could you please have a lookk at this?

**Comment by jrcpereira** [comment]
That's not a bug, but rather a security feature from iOS...

The browser implementation was done for Android only, not iOS.

You may want to check the `_logoutResult ` object for logout completion. When you choose `Cancel `in the dialog box you show, the logout doesn't complete as it is suposed.

**Comment by vdecristofaro** [comment]
Yes, I know it was done for Android. Thanks a lot for your quick answer.

While I can understand the need for the security feature I can’t understand what was passing in the mind of the programmer when he choosed ti inform the that a login is going to happen when the user chooses to make a logout instead :)

This is really horrible, isn’t it?

**Comment by softsan** [comment]
```
var logoutResult = await _client.LogoutAsync(new LogoutRequest()
            {
                BrowserDisplayMode = DisplayMode.Hidden,
                IdTokenHint = _identityToken;
            });
```
@leastprivilege  @jrcpereira @vdecristofaro  Tried above code to hide the browser window but it still shows it. Any thoughts on that?
Also is there any example of `RefreshTokenHandler` for Xamarin?
Thanks.
