### ISSUE TITLE
Why can't we use HttpClient instead of System Browser?

### ISSUE THREAD

**Issue by itsho** [IdentityModel/IdentityModel.OidcClient.Samples#81]
Hi.

We are using system browser in this case:

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/48a765c8318b2d449583c47dc6bd5c8f7902e63a/ConsoleSystemBrowser/ConsoleSystemBrowser/Program.cs#L53

Is it possible to utilize `System.Net.Http.HttpClient` and keep a _Cookie Jar_ for later use - **instead** of a real browser?

Thank you very much in advance! 👍

**Comment by leastprivilege** [comment]
How do you want to show the login UI in this case? OIDC is inherently browser-based.

**Comment by itsho** [comment]
If possible, I like to show my own UI controls and to pass user and PW to the HttpClient.

Thanks!

**Comment by leastprivilege** [comment]
Then you don't do OpenID Connect  - and thus don't need this library.

**Comment by itsho** [comment]
Please excuse my ignorance, can you elaborate why I don't need this library?

My server side requires authentication, and it's oidc compliance. Why do I must show a browser to the user?

**Comment by leastprivilege** [comment]
Because the whole point of OIDC is to move the authentication flow to the provider. The client should not be able to "see" the user's credentials.

Check the spec
https://openid.net/specs/openid-connect-core-1_0.html

**Comment by leastprivilege** [comment]
Oh and don't get me wrong - you totally can use HttpClient and "fake" the browser interaction

* post data
* maintain state with cookies
* follow redirects

etc...

does that feel right to you?

**Comment by itsho** [comment]
I understand.
just to make it clear - if I do use HttpClient, is it non-compliant with OIDC?

**Comment by itsho** [comment]
Can you please answer my question?
