### ISSUE TITLE
ClientId "native.code" not found on Identity Server demo for NetCoreConsoleClient sample

### ISSUE THREAD

**Issue by ChrisProlls** [IdentityModel/IdentityModel.OidcClient.Samples#82]
I mostly get the code of the NetCoreConsoleClient sample, and the important part :
```csharp
var options = new OidcClientOptions
            {
                Authority = _authority,
                ClientId = "native.code",
                RedirectUri = redirectUri,
                Scope = "openid profile api",
                FilterClaims = false,
                Browser = browser,
                Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode,
                ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect
            };
``` 

But I can't found the Identity Server configuration for the ClientId `native.code`. If I check at the Identity Server demo GitHub, there is no client called `native.code` configured : https://demo.identityserver.io/.

Any idea ? 
Thanks

**Comment by leastprivilege** [comment]
It was renamed to `interactive.public` at some point. Feel free to fix via PR.

thanks!

**Comment by ChrisProlls** [comment]
Sended !
