### ISSUE TITLE
Testing Android client, on "Login" getting "...unauthorized_client Unknown client or client not enabled"

### ISSUE THREAD

**Issue by tinonetic** [IdentityModel/IdentityModel.OidcClient.Samples#84]
Hi,

I tried the Xamarin Android client 

I am getting an error from IdentityServer when I click login in the Android App client

I am guessing that the App has outdated configs.

1. Which are the right client configs?
2. Also, is there a solution for the server identity, in case I would like to play with it locally?

### Login

![image](https://user-images.githubusercontent.com/8109147/99779591-f175b080-2b1d-11eb-8f9a-b1432d606464.png)

### Error
![image](https://user-images.githubusercontent.com/8109147/99776568-afe30680-2b19-11eb-959f-a253ad629a26.png)

**Comment by leastprivilege** [comment]
The sample client configs can be found here:
https://demo.identityserver.io/

You want to use "interactive.public"
