### ISSUE TITLE
How to set the RedirectUri for desktop app(WPF) in production?

### ISSUE THREAD

**Issue by bazen-teklehaymanot** [IdentityModel/IdentityModel.OidcClient.Samples#89]
Hi, I have a question regarding the RedirectUrl when implementing the authentication for desktop app. when its local(for development & testing) simply setting the value to localhost([such as this](https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/ea5ea443f91d667223ede870787794fa16af8f46/WpfWebView/WpfWebView/MainWindow.xaml.cs#L34) ) will suffice, however if it is in production it's a bit confusing for me what to set the value of RedirectUri in the desktop app. I was hoping if you can help me with this?

**Comment by leastprivilege** [comment]
https://tools.ietf.org/html/rfc8252#section-7
