### ISSUE TITLE
AndroidClientChromeCustomTabs crashes if Login tried after an already successful Login on Android 7

### ISSUE THREAD

**Issue by ChrisTowles** [IdentityModel/IdentityModel.OidcClient.Samples#9]
Steps to Reproduce 

OS: Android 7.1.1
Chrome: 53+

* Press 'Login'
* Chrome will Open 
* Enter Bob\Bob
* Press 'Call API'
* Press 'Login'
* Chrome will Open 
* Chrome Closes
* **CRASH** - Left at Home screen 

![androidclientchromecustomtabs crash in 7.1.1](https://cloud.githubusercontent.com/assets/3102683/20979768/0ebe32bc-bc7c-11e6-85a3-2595db8bcc05.gif)

Works on Android 4.4 and 5.1

**Comment by leastprivilege** [comment]
see #7

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
